### ISSUE TITLE
Support automatic activation

### ISSUE THREAD

**Issue by sntran** [19h47/19h47-tabs#3]
Per [Deciding When to Make Selection Automatically Follow Focus](https://www.w3.org/TR/wai-aria-practices/#kbd_selection_follows_focus), the tabs should be activated automatically when the content of the tab panels is present in the DOM, and manual activation is used when there is network request involved.

It would be nice to support both cases.

**Comment by 19h47** [comment]
Hello @sntran, thanks for your issue.

In fact this is an option called `delay` but not documented. 😞 

By default selection doesn't follow automatically the focus, if you pass a delay to constructor, selection follow focus with this delay.

I updated README and example. Hope it's what you'r talking about.

**Comment by sntran** [comment]
Hi! I found that out also after reading the source. Thanks for update the documentation!
